// Piezas de arte de la tortuga (Docs/Arte_Assets.md, «La tortuga»): mallas estáticas que no genera el código, sino que se
// pegan a un hueso de la malla del personaje y siguen su animación, en el jugador y en todas sus copias (tendero, general,
// escaparate de cosméticos y podio). Sin malla en el catálogo no hay pieza. Formato en TN_ArtSlots_Lobby.inl; el hueso por
// defecto de cada una está en TNTurtleArt::GetPieces (Art/TN_TurtleArt.cpp) y se cambia con Bone en el catálogo.

TN_ART_SLOT("Turtle.Shell", "Hueso", "Art/TN_TurtleArt.cpp", "Caparazón de la tortuga; sigue al hueso Spine1 (la mitad de la espalda). No lleva los colores ni el dibujo de los caparazones de la tienda", "El de la malla del personaje: la de demo mide 53 de alto (133 cm en el juego, que la escala x2,5); su caparazón va de Z = 22 a 38 y de Y = -9 a 3", "El origen de la malla del personaje (entre los pies, +Z arriba, mira a +Y como la de demo): exporta la pieza junto al cuerpo, sin mover el pivote")
TN_ART_SLOT("Turtle.Helmet", "Hueso", "Art/TN_TurtleArt.cpp", "Casco de serie; sigue al hueso Head. Sustituye al casco rojo pintado en la malla de demo y se esconde mientras se lleva un casco de la tienda", "El de la malla del personaje: en la de demo la coronilla está a Z = 51", "El origen de la malla del personaje, como Turtle.Shell")
TN_ART_SLOT("Turtle.Eyes", "Hueso", "Art/TN_TurtleArt.cpp", "Ojos; siguen al hueso Head. Fijos: no parpadean ni cambian con los ojos de la tienda (eso solo lo hace la malla de demo, que los lleva pintados)", "El de la malla del personaje: en la de demo los ojos van de Z = 42 a 50", "El origen de la malla del personaje, como Turtle.Shell")
TN_ART_SLOT("Turtle.Tongue", "Hueso", "Art/TN_TurtleArt.cpp", "Lengua fija; sigue al hueso Head. Con la malla de demo la cara dibuja además su lengua animada", "El de la malla del personaje: en la de demo la boca está en Z = 41 a 44, delante en Y = 10 a 14", "El origen de la malla del personaje, como Turtle.Shell")
