// Piezas de arte del parque de pruebas y los puestos del lobby (Docs/Arte_Assets.md). Formato en TN_ArtSlots_Lobby.inl.

// ── Parque de pruebas: piezas de ATN_PlaygroundPiece (una por tipo; se modelan con las medidas por defecto y se estiran a las de cada copia) ──
TN_ART_SLOT("Lobby.Playground.BucketPost", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Poste de cubos de playa boca abajo apilados (colores alternos, asa y nervios) con una estrella de mar en la cima", "Radio 64 abajo y 49 arriba, 180 de alto (3 cubos de 60); se estira en alto con PostHeight", "Centro de la base en el suelo; +X hacia delante del actor")
TN_ART_SLOT("Lobby.Playground.PopsicleSteps", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Escalón de 3 bloques forrados de palitos de helado (algunos teñidos), cada uno 36 más alto que el anterior", "180 de largo (3 x 60), 120 de ancho y 108 de alto; se estira a StepCount x StepDepth, StepWidth y StepCount x StepHeight", "Borde de abajo del primer escalón (X = 0) a ras de suelo y centrado en el ancho; +X hacia donde suben los escalones")
TN_ART_SLOT("Lobby.Playground.ShellSlide", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Tobogán de vieira tumbada (nácar arriba, costillas de color por debajo) sobre un montón de arena, con plataforma de arena en la charnela, almenas, banderín y escalera de arena hacia atrás", "Concha de 151 de largo y 160 de alto en la charnela (46 grados), labio de 190 de ancho; plataforma de 90 de fondo y 140 de ancho; escalera de 3 peldaños de 45; se estira con SlideHeight, SlideAngle y SlideWidth", "Charnela de la concha (X = 0) a ras de suelo y centrada en Y; +X cuesta abajo hacia el labio, la plataforma y la escalera quedan en -X")
TN_ART_SLOT("Lobby.Playground.ShellSlideNoSteps", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "El mismo tobogán de vieira pero sin la escalera de arena de detrás (bSlideSteps desactivado)", "Igual que ShellSlide sin la escalera: concha de 151 de largo y 160 de alto, plataforma de 90 de fondo", "Igual que ShellSlide: charnela (X = 0) a ras de suelo; +X cuesta abajo")
TN_ART_SLOT("Lobby.Playground.CookiePlatform", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Galleta de chocolate grande con pepitas y azúcar sobre una columna de galletas rellenas de crema", "Galleta de 230 de diámetro y 17 de grueso sobre columna de 104 de diámetro, 140 de alto; se estira con CookieRadius y PlatformHeight", "Centro de la columna en el suelo; +X hacia delante del actor")
TN_ART_SLOT("Lobby.Playground.CastleTunnel", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Túnel de castillo de arena: muro con almenas y marcas de cubo, bocas en arco con reborde y concha, bóveda lisa por dentro, camino de piedrecitas y banderín en lo alto", "220 de largo, 264 de ancho y 262 de alto (hueco de 184 de ancho y 178 a 225 de alto), con banderín hasta 372; se estira en largo con TunnelLength", "Centro del túnel en el suelo; el túnel va a lo largo de X (bocas en X = ±110)")
TN_ART_SLOT("Lobby.Playground.SpadeSpinnerHub", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Cubo del centro de la barra giratoria de pala: tronco de cono de color con reborde (no gira; las palas, el collar y la tapa son SpadeSpinnerArms)", "Radio 40 abajo y 32 arriba, 50 de alto", "Centro de la base en el suelo; eje de giro de las palas")
TN_ART_SLOT("Lobby.Playground.SpadeSpinnerArms1", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Parte que gira de la barra de pala con 1 brazo: collar amarillo alrededor del cubo, tapa con remolino, mango con puño y cuello y hoja vertical redondeada", "Brazo de 230 desde el eje, mango a 30 del suelo y hoja de 46 de largo y 39 de alto; se estira con ArmLength y ArmHeight", "Eje de giro (centro del cubo) a ras de suelo; el brazo sale hacia +X en el ángulo de inicio y el código gira toda la pieza")
TN_ART_SLOT("Lobby.Playground.SpadeSpinnerArms2", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Parte que gira de la barra de pala con 2 brazos (la de serie): collar amarillo, tapa con remolino y dos mangos con hoja redondeada, opuestos", "Dos brazos de 230 desde el eje (460 de punta a punta), mango a 30 del suelo y hojas de 46 x 39; se estira con ArmLength y ArmHeight", "Eje de giro (centro del cubo) a ras de suelo; un brazo hacia +X y el otro hacia -X, el código gira toda la pieza")
TN_ART_SLOT("Lobby.Playground.SpadeSpinnerArms3", "Componente", "Lobby/Playground/TN_PlaygroundPiece.cpp", "Parte que gira de la barra de pala con 3 brazos: collar amarillo, tapa con remolino y tres mangos con hoja redondeada a 120 grados", "Tres brazos de 230 desde el eje, mango a 30 del suelo y hojas de 46 x 39; se estira con ArmLength y ArmHeight", "Eje de giro (centro del cubo) a ras de suelo; un brazo hacia +X y los otros a 120 y 240 grados, el código gira toda la pieza")

// ── Parque de pruebas: medusa trampolín (ATN_JellyfishTrampoline) y puente tambaleante (ATN_WobblyBridge) ──
TN_ART_SLOT("Lobby.Playground.Jellyfish.Bell", "Componente", "Lobby/Playground/TN_JellyfishTrampoline.cpp", "Campana de gelatina de la medusa cama elástica con cara, motas, trébol de órganos y brillo (los tentáculos se mecen con una malla que se deforma en cada fotograma y no son sustituibles)", "Radio 110 en el borde y 82 de alto sobre el borde, con Size 1; se escala con Size (0,5 a 2,5)", "Centro del borde de la campana (a 42 de la arena con Size 1); +X hacia la cara; la campana se aplasta y rebota sobre este punto")
TN_ART_SLOT("Lobby.Playground.Bridge.Frame", "Componente", "Lobby/Playground/TN_WobblyBridge.cpp", "Marco del puente colgante: 4 postes con cuerda enrollada, bola y banderín, 2 torres de arena con almenas y estrellas, concha en la cara de fuera y escalera de arena (el tablero y las cuerdas se mueven en cada fotograma y no son sustituibles)", "Con SpanLength 900, DeckHeight 220 y DeckWidth 110: 1630 de largo con las escaleras de 5 peldaños de 45, torres de 140 de fondo y 170 de ancho con la cima a 220, postes hasta 400; se estira con los tres", "Centro del vano en el suelo; el puente va a lo largo de X (postes en X = ±462, tablero entre X = ±450 a 220 de alto)")
TN_ART_SLOT("Lobby.Playground.Bridge.FrameNoStairs", "Componente", "Lobby/Playground/TN_WobblyBridge.cpp", "Marco del puente colgante con las torres de arena pero sin las escaleras (bStairs desactivado)", "Igual que Bridge.Frame sin escaleras: 1180 de largo con SpanLength 900", "Igual que Bridge.Frame: centro del vano en el suelo, el puente a lo largo de X")
TN_ART_SLOT("Lobby.Playground.Bridge.FramePosts", "Componente", "Lobby/Playground/TN_WobblyBridge.cpp", "Marco del puente colgante sin torres (bSandTowers desactivado): solo los 4 postes con cuerda, bola y banderín, que nacen del suelo", "4 postes de 330 de alto (hasta 400 con el banderín) a ±462 en X con SpanLength 900", "Igual que Bridge.Frame: centro del vano en el suelo, el puente a lo largo de X")

// ── Probador, tendero y vista previa de cosméticos ──
TN_ART_SLOT("Lobby.Booth.Bottle", "Componente", "Lobby/TN_ChangingBooth.cpp", "Probador: media botella de plástico verde azulado boca abajo, con la pared curva, el hueco redondo de la puerta con su boca de vidrio grueso, el techo con el culo de cinco pies, la etiqueta de refresco (las letras son aparte), el canto del corte y dentro la tarima de tablones con una alfombra redonda", "Radio 150 y 305 de alto en la pared, 375 con los pies del techo; hueco de la puerta de radio 88 centrado a 114", "Centro de la botella a ras de suelo; la puerta mira a +X")
TN_ART_SLOT("Lobby.Booth.Door", "Componente", "Lobby/TN_ChangingBooth.cpp", "Puerta del probador: chapa de corona roja con anillo crema, estrella dorada en relieve, falda rizada de 21 pliegues y forro de dentro; gira sobre su bisagra al abrirse", "Disco de unos 190 de diámetro y unos 25 de fondo con el relieve y el forro", "Bisagra a ras de suelo, en el lado -Y de la chapa sobre la pared; ejes de la botella (cerrada, la cara mira a +X); se abre girando -108 grados en Z")
TN_ART_SLOT("Lobby.Shop.Stall", "Componente", "Lobby/TN_ShopKeeper.cpp", "Puesto del tendero entero: mostrador de tablones con franja coral, toldo de rayas con volante de picos, cartel azul con marco dorado (el texto es aparte), guirnalda de banderines, estantería del fondo con botes de pintura, caparazones, tarros con ojos y cascos, perchero con sombreros, barril con pala, cajas con conchas, farol y cofre con monedas", "Unos 800 de ancho, 360 de fondo y 380 de alto con StallScale 1 (el componente se escala con StallScale)", "Suelo bajo el tendero (en el origen); la tienda mira a +X hacia los clientes; el mostrador está en X = 125")
TN_ART_SLOT("Lobby.CosmeticPreview.Pedestal", "Componente", "Lobby/TN_CosmeticPreview.cpp", "Islita de arena con canto de roca, una estrella de mar y dos conchas sobre la que posa la tortuga de la vista previa de cosméticos (solo se ve en la captura del escaparate)", "Unos 132 de diámetro y 48 de alto (de -34 a 14 en Z)", "Eje del giratorio del escaparate; la cara de arriba, donde pisa la tortuga, está a 12 sobre el origen; +X mira a la cámara")
