// Piezas de arte heredadas del mapa procedural que siguen en uso (Docs/Arte_Assets.md): la estructura de salida con los
// huevos, los puzles, el géiser y los actores de agua. Formato en TN_ArtSlots_Lobby.inl.

// ── Estructura de salida (ATN_ProcStartStructure): la misma puerta doble y pila de huevos que el lobby, en locales de la estructura ──
TN_ART_SLOT("ProcMap.Start.Gatehouse", "Pieza", "Lobby/TN_CastleKit.h", "Puerta doble de la salida: suelo, dos fachadas con arco y cartel, sala con conchas y antorchas, dos torres grandes y dos torreones (las hojas van aparte)", "2060 de ancho con las torres, 700 de fondo, fachadas de 760 y torres de 1350; los muros bajan 450 bajo el suelo", "Centro del umbral de la puerta 1 en el origen de la estructura; +Y hacia la puerta 2 (el camino)")
TN_ART_SLOT("ProcMap.Start.EggMound", "Pieza", "Lobby/TN_CastleKit.h", "Montículo de dos alturas de la pila de huevos de la salida, con el escalón de la concha", "Radio 480 y 60 de alto; piso alto de radio 175 y 200 de alto", "Centro del montículo en el suelo (Z = 4); +X hacia el camino")
TN_ART_SLOT("ProcMap.Start.EggCup", "Pieza", "Lobby/TN_CastleKit.h", "Base de cada huevo de la salida (8): media cáscara con borde en zigzag y nido de paja", "Radio 97, 110 de alto", "Centro de la base del huevo")
TN_ART_SLOT("ProcMap.Start.EggLid", "Componente", "Lobby/TN_CastleKit.h", "Tapa de cada huevo de la salida (8); salta dando vueltas y se esfuma al romperse el huevo", "Radio 96, 128 de alto", "Centro de la costura (el borde de abajo)")
TN_ART_SLOT("ProcMap.Start.GateLeaf", "Componente", "Lobby/TN_CastleKit.h", "Hoja de madera de la puerta doble de la salida (4); las de la puerta 2 giran al abrirse", "430 de ancho, 540 de alto, 30 de grueso", "Bisagra (borde de abajo); la hoja va hacia +X")

// ── Actores del mapa: puzles, géiser y agua (mallas del motor o generadas en un componente suelto) ──
TN_ART_SLOT("ProcMap.Puzzle.ThrowWallBlock", "Componente", "World/ProcMap/TN_ProcPuzzleActors.cpp", "Muro de lanzamiento: el bloque (hoy el cubo del motor)", "Cubo de 100 escalado a largo x ancho x alto del muro (desde 300 x 300 x 200): modélalo como un cubo de 100, la malla de arte hereda esa escala", "Centro del cubo")
TN_ART_SLOT("ProcMap.Puzzle.ThrowWallRamp", "Componente", "World/ProcMap/TN_ProcPuzzleActors.cpp", "Rampa del muro de lanzamiento que baja al pulsar el interruptor (hoy el cubo del motor); gira sobre su bisagra", "Cubo de 100 escalado al largo de la rampa x 45 % del ancho del muro x 30: la malla de arte hereda esa escala", "Centro del cubo (la bisagra es su padre). Sin colisión de arte: el código enciende y apaga la suya")
TN_ART_SLOT("ProcMap.Puzzle.SabotageGate", "Componente", "World/ProcMap/TN_ProcPuzzleActors.cpp", "Compuerta de sabotaje que sube del suelo (hoy el cubo del motor)", "Cubo de 100 escalado a 120 x ancho x alto de la compuerta: la malla de arte hereda esa escala", "Centro del cubo")
TN_ART_SLOT("ProcMap.Puzzle.Switch", "Componente", "World/ProcMap/TN_ProcPuzzleActors.cpp", "Interruptor de los puzles (hoy el cilindro del motor, rojo o verde según su objetivo; el tinte no llega a la malla de arte)", "Cilindro de 100 x 100 con escala 0,6 x 0,6 x 0,4: la malla de arte hereda esa escala", "Centro del cilindro (raíz del actor)")
TN_ART_SLOT("ProcMap.Geyser.Mound", "Componente", "World/ProcMap/TN_ProcTraversalActors.cpp", "Montículo de sínter del géiser: terrazas concéntricas, poza turquesa, boca y piedras alrededor (con colisión: se sube como un escalón)", "Radio 300 (piedras hasta 350), 41 de alto", "Centro de la base en el suelo")
TN_ART_SLOT("ProcMap.Geyser.Jet", "Componente", "World/ProcMap/TN_ProcTraversalActors.cpp", "Chorro de agua del géiser (M_ProcCascade, agua que corre hacia arriba); el código lo estira con el pulso", "Radio 95 en la base y 100 de alto a escala 1: el Tick lo escala a la altura del chorro", "Centro de la base, 30 sobre el suelo; Z arriba")
TN_ART_SLOT("ProcMap.Geyser.FoamCap", "Componente", "World/ProcMap/TN_ProcTraversalActors.cpp", "Corona de espuma en lo alto del chorro (sube y crece con él)", "Racimo de bolas de radio 62, bolas de unos 50", "Centro del racimo, en la cima del chorro")
TN_ART_SLOT("ProcMap.Geyser.FoamRing", "Componente", "World/ProcMap/TN_ProcTraversalActors.cpp", "Espuma de la boca del géiser (late con el chorro)", "Anillo de radio 128 con bolas de unos 40", "Centro de la boca, 36 sobre el suelo")
TN_ART_SLOT("ProcMap.Water.CurrentMarker", "Componente", "World/ProcMap/TN_ProcWaterActors.cpp", "Marca de una corriente de agua: cono tumbado que avanza con ella (hoy el cono del motor; 3 por corriente)", "Cono de 100 con escala 0,35 x 0,35 x 0,5: la malla de arte hereda esa escala", "Centro del cono; el código lo tumba para que apunte con la corriente")
TN_ART_SLOT("ProcMap.Water.WhirlpoolDisc", "Componente", "World/ProcMap/TN_ProcWaterActors.cpp", "Disco oscuro del remolino que gira (hoy el cilindro del motor)", "Cilindro de 100 escalado a radio/50 x radio/50 x 0,02 (el diámetro del remolino y 2 de alto): la malla de arte hereda esa escala", "Centro del disco, 3 sobre el agua")
TN_ART_SLOT("ProcMap.Water.PredatorFin", "Componente", "World/ProcMap/TN_ProcWaterActors.cpp", "Aleta del depredador del agua (hoy el cono del motor)", "Cono de 100 con escala 0,9 x 0,25 x 0,9: la malla de arte hereda esa escala", "Centro, 45 sobre la raíz; +X hacia donde nada")
TN_ART_SLOT("ProcMap.Water.PredatorBody", "Componente", "World/ProcMap/TN_ProcWaterActors.cpp", "Cuerpo del depredador bajo el agua (hoy la esfera del motor)", "Esfera de 100 con escala 3,2 x 1,1 x 0,9: la malla de arte hereda esa escala", "Centro, 40 bajo la raíz; +X hacia donde nada")
TN_ART_SLOT("ProcMap.Water.Jellyfish", "Componente", "World/ProcMap/TN_ProcWaterActors.cpp", "Medusa saltarina (trampolín por arriba); hoy la esfera del motor o la malla de su variante, teñida (el tinte no llega a la malla de arte)", "Esfera de 100 con escala 2,4 x 2,4 x 1,2 que se balancea y se aplasta: la malla de arte hereda esa escala", "Centro del cuerpo")
