# Datos del roadmap macro-update. Campos:
# id, titulo, desc, hmin, hmax, deps, quien, criterio, ref, carril, tipo, ola, estado, fase
# tipo: CPP (compila UE) | PY | ART | DOC | MAN (Rodrigo/PIE/Steam) | EXT (equipo externo, 0 h agente)
# estado: pend | curso | hecho | cond (condicional, fuera del total)
# fase: MVP | Despues

EPICS = {
    "E0": "Infraestructura, arquitectura común y sistema de bugs",
    "E1": "Steam y producto",
    "E2": "Terreno y mapas",
    "E3": "Foto→Mapa",
    "E4": "Coop",
    "E5": "Carrera",
    "E6": "Rally Tortuga",
    "E7": "Todos contra Todos",
    "E8": "2 vs 2",
    "E9": "Física de la tortuga",
    "E10": "Red, sincronización hasta 8 y voz",
    "E11": "Optimización y estrés",
    "E12": "Interfaz y efectos comunes",
    "E13": "Assets (IA → modeladores)",
    "E14": "Limpieza y calidad de código",
    "E15": "Localización, logros y ajustes",
    "E16": "Playtests y QA",
}

OLAS = {
    1: "Arranque: integrar lo pendiente y base Steam (F0)",
    2: "Terreno preparado (F1), sistema de bugs, tortuga y red en paralelo",
    3: "Coop Prepared (F2) y retirada de Run",
    4: "Arquitectura común de modos y Carrera",
    5: "Rally: núcleo del buggy y backend",
    6: "Coop: reglas, puzzles, enemigos e interfaz",
    7: "Todos contra Todos (MVP)",
    8: "2 vs 2 (MVP)",
    9: "Rally: mapas, biplaza y pulido",
    10: "Mapas, Foto→Mapa y contenido",
    11: "Optimización, red a 8 y voz",
    12: "Limpieza y calidad",
    13: "Cierre Steam, localización y playtests finales",
    14: "Después (no bloquea la 1.0)",
}

T = [
# ---------------- E0 ----------------
("E0-01","Integrar PR #9 (bugs de la nube)","Compilar DebugGame, pasar tests y fusionar en macro-update",2,3,"—","UE + Rodrigo (PIE 4P)","Build verde, tests Tortunabo.* verdes, PIE 4P sin errores nuevos en log","Docs/Reviews/nube/integracion-2026-09-29.md","INT","CPP",1,"pend","MVP"),
("E0-02","Categorías de log por sistema","LogTNMatch, LogTNItems, LogTNShell, LogTNNet, LogTNRally, LogTNPuzzle con prefijo de máquina","2","3","E0-01","UE","`log LogTNItems Verbose` filtra; cada línea lleva Servidor/Cliente N","specs/modos/00 §2","FW","CPP",2,"pend","MVP"),
("E0-03","CVars TN.Debug.<Sistema>","Dibujo de estado en pantalla por sistema (patrón TN.Shell.Debug)",3,4,"E0-02","UE","≥ 5 sistemas con `TN.Debug.X 1` sin recompilar","specs/modos/00 §2","FW","CPP",2,"pend","MVP"),
("E0-04","Invariantes con ensureMsgf","Dos dueños, pawn bajo el terreno, fase sin salida","2","3","E0-02","UE","Test que fuerza cada invariante y deja traza con estado completo","specs/modos/00 §2","FW","CPP",2,"pend","MVP"),
("E0-05","Detector de desincronía","Hash del estado crítico cada 2 s; el cliente registra [Desync] con el campo","5","7","E0-02","UE","Desfase provocado por cvar → [Desync] con el campo correcto en PIE 2P","specs/modos/00 §2","FW","CPP",2,"pend","MVP"),
("E0-06","Informe de bug con F8","Captura, 2000 líneas de log, JSON de GameState y jugador, semilla, mapa, commit","4","6","E0-02","UE","F8 crea Saved/BugReports/<fecha>/ con los 5 ficheros en PIE y Shipping","specs/modos/00 §2","FW","CPP",2,"pend","MVP"),
("E0-07","Repeticiones en playtest","demorec/demoplay documentados y cvar de grabación automática","1","2","—","UE","Una partida de 4 grabada y reproducida","specs/modos/00 §2","FW","CPP",2,"pend","MVP"),
("E0-08","Telemetría de playtest a CSV","Muertes, rescates, objetos, tiempos de tramo","3","4","E0-14","UE","CSV con ≥ 6 tipos de evento tras una partida","specs/modos/00 §2","FW","CPP",4,"pend","MVP"),
("E0-09","Máquina de fases de partida","ETNMatchPhase Lobby→Carga→Cuenta→Juego→Cierre→Resultados→Siguiente, replicada y con tiempo máximo","6","8","E4-11","UE","Test: cada fase sale por tiempo máximo; fase replicada en 4 máquinas","specs/modos/00 §1","FW","CPP",4,"pend","MVP"),
("E0-10","Estrategia de modo UTN_ModeRules","Coop base; Carrera y 2 vs 2 heredan; el GameMode no conoce modos","8","10","E0-09","UE","Coop y Carrera arrancan con su UTN_ModeRules; 0 switch por modo en el núcleo","specs/modos/00 §1","FW","CPP",4,"pend","MVP"),
("E0-11","DataAssets de datos","UTN_ItemDef, UTN_PuzzleTemplate, UTN_ModeDef, UTN_MapDef","6","8","E0-10","UE","Un objeto nuevo = un DataAsset; test de carga de los 4 tipos","specs/modos/00 §1","FW","CPP",4,"pend","MVP"),
("E0-12","Mensajería de gameplay","Objeto usado, jugadora fuera, puzzle resuelto, sabotaje; UI/FX/telemetría escuchan","4","6","E0-10","UE","Gameplay sin llamadas directas a UI en los 4 eventos","specs/modos/00 §1","FW","CPP",4,"pend","MVP"),
("E0-13","Interfaz ITN_Activatable","Placas, palancas, botones → puertas, géiseres, plataformas","3","4","E0-11","UE","Placa activa puerta y géiser sin código específico (test)","specs/modos/00 §1","FW","CPP",4,"pend","MVP"),
("E0-14","Pool de objetos","Proyectiles, cajas, efectos, marcas de rueda","3","4","E0-11","UE","0 spawn/destroy por disparo en stat; tamaño de pool por mapa","specs/modos/00 §1","FW","CPP",4,"pend","MVP"),
("E0-15","Test de partida completa headless por modo","Bots de principio a fin, uno por modo","4","6","E0-10","test-automator","1 test verde por modo implementado","specs/modos/00 §2","FW","CPP",4,"pend","MVP"),
("E0-16","Fusión final macro-update → main","PR con historial completo, resumen y plan de pruebas","3","4","E16-12","devops-engineer + Rodrigo","PR aprobada, CI verde, main compila","CLAUDE global (Git)","INT","MAN",13,"pend","MVP"),
("E0-17","Sincronizar documentos con las decisiones vigentes","Jugadoras por modo, cierres de carrera, nº de modos, assets imprescindibles, objetos TcT, torbellino, Mapa01 en memoria","1","2","—","agente de documentación","0 contradicciones abiertas de la tabla C de la auditoría","Docs/Auditoria-Cobertura-2026-09-29.md §3","DOC","DOC",1,"pend","MVP"),
# ---------------- E1 ----------------
("E1-01","F0-T1 Guardia de cocinado","Pytest que exige mapas de juego y /Game/Coop en el paquete","1","1","—","UE","Pytest rojo si falta LVL_Lobby o LVL_BeachRace","plans/F0-F2 T1","ST","PY",1,"pend","MVP"),
("E1-02","F0-T2 Source/Logs fuera del repo","Verificación","0","0","—","—","Hecho en macro-update","plans/F0-F2 T2","ST","DOC",1,"hecho","MVP"),
("E1-03","F0-T3 OnTravelFailure","Vuelta al lobby (anfitrión) o al menú (invitado) con mensaje","4","4","E0-01","UE","Viaje a mapa inexistente → menú con mensaje en 2 máquinas","plans/F0-F2 T3","ST","CPP",1,"pend","MVP"),
("E1-04","F0-T4 AppID configurable y bloqueo del 480","AppID por config; Shipping rechaza 480; quitar filtro de salas","3","3","—","UE","Shipping con 480 falla al arrancar; filtro eliminado","plans/F0-F2 T4","ST","CPP",1,"pend","MVP"),
("E1-05","Trámite Steamworks","Cuenta, pago, AppID propio, depósitos (Valve tarda semanas)","2","4","—","Rodrigo","AppID propio asignado","Plan maestro §4 P0","ST","MAN",1,"pend","MVP"),
("E1-06","F0-T5 N-A depuración remota","RPC del fantasma solo en editor o con cvar","1.5","1.5","—","UE","Invitado en Development no ejecuta comandos sin cvar","plans/F0-F2 T5","ST","CPP",1,"pend","MVP"),
("E1-07","F0-T7 CI local","build_check.bat relativo, BuildCookRun + Automation por PR a macro-update","8","8","E1-01","devops-engineer","CI verde con los 97 tests en un PR de prueba","plans/F0-F2 T7","ST","CPP",1,"pend","MVP"),
("E1-08","F0-T8 Playtest Shipping con dos máquinas","Lobby → carrera → menú en build empaquetada","4","4","E1-01,E1-03,E1-04,E1-07","Rodrigo + UE","Checklist completo sin cuelgues","plans/F0-F2 T8","QA","MAN",1,"pend","MVP"),
("E1-09","Cocinado completo verificado","Cook entero y revisar LoadObject fallidos (Limpieza 2.8, Calidad H4)","2","3","E1-01","UE","0 «Failed to load» en la build cocinada","Limpieza §2.8; Calidad H4","ST","CPP",1,"pend","MVP"),
("E1-10","N-D ServerGoToStation validado","Validar índice en el servidor","1","1","—","UE","Índice fuera de rango rechazado (test)","F_gaps_steam §3","ST","CPP",1,"pend","MVP"),
("E1-11","Guardado asíncrono y Steam Cloud","Resto de P2 de guardados (versión ya hecha en 0d393c6f6)","3","4","—","UE","Guardado sin bloqueo del hilo; Cloud activo en Steamworks","F_gaps_steam #4","ST","CPP",13,"pend","MVP"),
("E1-12","Steam Deck y mando","Teclado virtual para el código de sala, glifos, prueba en Deck","20","20","E1-08","UE + Rodrigo (Deck)","Partida completa en Deck solo con mando","F_gaps_steam #7","ST","CPP",13,"pend","MVP"),
("E1-13","Créditos y licencias","Noto OFL, audio de terceros, fuentes MDE, HellYeah","8","8","—","UE","Pantalla de créditos con todas las fuentes listadas","F_gaps_steam #12; Plan §6","ST","CPP",13,"pend","MVP"),
("E1-14","Icono y splash","Build/Windows con .ico y splash","4","4","E13-05","UE + equipo de arte","Shipping muestra icono y splash propios","F_gaps_steam #9","ST","CPP",13,"pend","MVP"),
("E1-15","Página de tienda","Textos en 13 idiomas, capturas, tráiler, cápsulas","6","10","E13-05","Rodrigo + game-designer","Página enviada a revisión de Valve","Plan maestro §3.6","ST","MAN",13,"pend","MVP"),
("E1-16","Perfil cosmético por cuenta de Steam (L3)","Slot por SteamID en vez de _Local","2","3","—","UE","Dos cuentas en el mismo PC no comparten desbloqueos","Calidad L3","ST","CPP",13,"pend","MVP"),
# ---------------- E2 ----------------
("E2-01","F1-T9 BFS con padres","Alcance con cota mínima y camino ordenado de P01","4","4","—","agente Python","Pytest del camino ordenado verde","plans/F0-F2 T9","PY","PY",2,"pend","MVP"),
("E2-02","F1-T10 Máscara y bake.bin","Muestreo del camino, ancho, safe_low/high","4","4","E2-01","agente Python","Pytest del formato TNCB verde","plans/F0-F2 T10","PY","PY",2,"pend","MVP"),
("E2-03","F1-T11 Manifest v2 (C01, P01)","Bloque coop y gen_terrain_coop.py","5","5","E2-02","agente Python","Manifest v2 de C01 y P01 validado","plans/F0-F2 T11","PY","PY",2,"pend","MVP"),
("E2-04","F1-T12 Decimado cuádrico","Presupuesto de malla con borde fijo","5","5","—","agente Python","C01 ≤ 1,1 M tri sin grietas en costuras","plans/F0-F2 T12","PY","PY",2,"pend","MVP"),
("E2-05","F1-T13 Rejilla horneada C++","ParseBake, IsAllowed, suelo en túnel","4","4","E0-01","UE","Tests IsAllowed y WalkableZAt en túnel verdes","plans/F0-F2 T13","CP","CPP",2,"pend","MVP"),
("E2-06","F1-T14 UTN_CoopMapData","LoadFromManifest","5","5","E2-05","UE","Test de carga del manifest de C01","plans/F0-F2 T14","CP","CPP",2,"pend","MVP"),
("E2-07","F1-T15 Vigilante puro","Lógica de rescate sin UObject","3","3","—","UE","Tests StepWatch y PickRescueSlot verdes","plans/F0-F2 T15","CP","CPP",2,"pend","MVP"),
("E2-08","F1-T16 Proveedor de suelo y Source=Prepared","ITN_SafeGroundProvider y subsistema","5","5","E2-05,E2-06,E2-07","UE","Subsistema resuelve el proveedor en C01","plans/F0-F2 T16","CP","CPP",2,"pend","MVP"),
("E2-09","F1-T17 FindOpenSandSpot consulta al proveedor","","3","3","E2-08","UE","Test de aparición en túnel sobre el suelo","plans/F0-F2 T17","CP","CPP",2,"pend","MVP"),
("E2-10","F1-T18 Vigilante de servidor y gaviotas por el camino","CourseBackAt","4","4","E2-07,E2-08","UE","20 lanzamientos fuera de zona → 20 rescates ≤ 1,75 s","plans/F0-F2 T18","CP","CPP",2,"pend","MVP"),
("E2-11","F1-T19 R1 terreno por etiqueta","","1.5","1.5","E2-05","UE","Ningún pawn congelado > 1 s al aparecer","plans/F0-F2 T19","CP","CPP",2,"pend","MVP"),
("E2-12","F1-T20 R2/R3 meta orientada y a cota","","2","2","E2-11","UE","Meta válida hacia −X y +Y (test)","plans/F0-F2 T20","CP","CPP",2,"pend","MVP"),
("E2-13","F1-T21 R5 SpawnFauna extraída","","3","3","—","UE","Fauna sin Layout.Modules (test)","plans/F0-F2 T21","CP","CPP",2,"pend","MVP"),
("E2-14","F1-T22 R8 pantalla de carga reconoce Coop","","1.5","1.5","—","UE","Pantalla de carga correcta al viajar a LVL_Coop_C01","plans/F0-F2 T22","CP","CPP",2,"pend","MVP"),
("E2-15","F1-T23 Marcadores y ancla","ATN_CoopMarker, ATN_CoopMapAnchor","2.5","2.5","E2-11","UE","Marcadores con id estable tras reimportar","plans/F0-F2 T23","CP","CPP",2,"pend","MVP"),
("E2-16","F1-T24 Importador headless","Subniveles _Terrain/_Markers/_Design, lápidas, TN_REGENERATE","7","7","E1-01,E2-03,E2-06,E2-08,E2-15","UE + agente Python","Reimportar no mueve marcadores ni resucita borrados","plans/F0-F2 T24","CP","CPP",2,"pend","MVP"),
("E2-17","F1-T25 R9 y smoke de LVL_Coop_C01 (gate F1)","Colisión de la malla fuente","2","2","E2-16","UE","Smoke headless sin ProcMesh; ningún cliente cocina colisión","plans/F0-F2 T25","CP","CPP",2,"pend","MVP"),
("E2-18","Re-horneado tras retoque manual del terreno","RebakeHeightsFromLevel: bake y máscara desde el terreno que editan los modeladores","8","12","E2-17","UE + agente Python","Terreno editado a mano → bake nuevo; rescate correcto en la zona editada","Foto→Mapa §5; P26–P27","CP","CPP",3,"pend","MVP"),
("E2-19","Puente de Mokius: localizar el asset con física","No está en Content; pedirlo a Mokius e importarlo","1","2","—","Rodrigo + Mokius","Asset en /Game con anclajes inicio/fin medidos","Plan §7.4; Coop Q6","CP","MAN",2,"pend","MVP"),
("E2-20","ATN_BridgeSpan sobre el puente de Mokius","Puente entre anclajes, cortable, replicado","16","24","E2-19","UE","Puente de 70 m colocado por marcador; corte igual en 4 máquinas","Plan §5 P4; TcT §3.5","CP","CPP",7,"pend","MVP"),
("E2-21","Países enteros miniaturizados (13)","Terminar country.py/countries.py (hoy 6 de 13) y validarlos","10","14","—","agente Python","13 países con lámina y validadores verdes","Catálogo §Decisión países; P33","PY","PY",2,"curso","MVP"),
("E2-22","Japón y Filipinas v2","Relieve real de Japón; Filipinas adaptada a TcT/Rally sin elevar relieve","4","6","E2-21","agente Python","Láminas L10_japon_v2 e I01_filipinas_v2 aprobadas por Rodrigo","P30–P31","PY","PY",2,"curso","MVP"),
("E2-23","Mapas inventados N01-N16","Kit de formas con semilla (lote C1 A02-A06 hecho)","16","24","—","agente Python","16 mapas con lámina y validadores verdes","gen_terrain_inventados.py; P38","PY","PY",2,"curso","MVP"),
("E2-24","Coliseo con bordes de agua","Arena TcT redonda con gradas y foso de agua","4","6","E2-23","agente Python","Mapa con lámina, 8 nidos y validadores verdes","P38 (OLVIDADO)","PY","PY",2,"pend","MVP"),
("E2-25","Actualizar el Catálogo de mapas","Países enteros, lote N, coliseo, estados reales","1","2","E2-21,E2-23","agente de documentación","Catálogo sin contradicciones con specs 03/04","Catalogo-Mapas","DOC","DOC",10,"pend","MVP"),
# ---------------- E3 ----------------
("E3-01","Esquema y validador de MapSketch.json","schema.py y validate.py","4","6","E2-03","agente Python","Pytest con 5 bocetos válidos y 5 inválidos","Foto→Mapa §4, §7","PY","PY",10,"pend","MVP"),
("E3-02","Análisis de imagen → boceto","Guía y ejemplos para que Claude lea la foto y escriba MapSketch.json","4","6","E3-01","game-designer + agente Python","3 fotos → 3 bocetos válidos revisados por Rodrigo","Foto→Mapa §3","PY","PY",10,"pend","MVP"),
("E3-03","Adaptador to_path","Boceto → generador camino","4","6","E3-01","agente Python","Boceto de prueba → mapa camino con validadores verdes","Foto→Mapa §7","PY","PY",10,"pend","MVP"),
("E3-04","Adaptadores to_island y to_arena","","6","8","E3-01","agente Python","Un boceto de isla y uno de arena generan mapa válido","Foto→Mapa §7","PY","PY",10,"pend","MVP"),
("E3-05","Expansor de marcadores y plantillas de puzzle","markers.py","6","8","E3-01,E0-11","agente Python","Las 15 plantillas del catálogo se expanden a actores","Foto→Mapa §6-7; Catálogo puzzles §7","PY","PY",10,"pend","MVP"),
("E3-06","Montaje del nivel desde el boceto","build_map_from_sketch.py headless: LVL_<id>, carpetas, FBX","8","12","E2-16,E3-05","UE + agente Python","Boceto → nivel abrible con marcadores en su carpeta","Foto→Mapa §7","CP","CPP",10,"pend","MVP"),
("E3-07","Pruebas de Foto→Mapa","","3","4","E3-06","test-automator","Pruebas de §9 verdes","Foto→Mapa §9","PY","PY",10,"pend","MVP"),
("E3-08","Piloto: boceto de Rodrigo → mapa Coop","Mapa Coop a partir de un dibujo del director","4","6","E3-06","game-designer + Rodrigo (lámina)","Rodrigo aprueba la lámina; recorrible en PIE","Foto→Mapa §1; P22","PY","PY",10,"pend","MVP"),
("E3-09","Guía para diseñadores y modeladores","Generar → retocar → re-hornear, sin que regenerar pise lo diseñado","2","3","E2-18,E3-06","agente de documentación","Guía en Docs con el flujo completo","P24–P27","DOC","DOC",10,"pend","MVP"),
# ---------------- E4 ----------------
("E4-01","F2-T26 Layout sintético","LayoutFromCoopData, R7","4","4","E2-15","UE","Test del layout desde el DA","plans/F0-F2 T26","CP","CPP",3,"pend","MVP"),
("E4-02","F2-T27 Construcción Prepared","R4, PreparedMapId, agua, fauna","6","6","E2-12,E2-13,E2-17,E4-01","UE","PreparedMapId alterado → error en log","plans/F0-F2 T27","CP","CPP",3,"pend","MVP"),
("E4-03","F2-T28 R6 SeaNear desde la rejilla","","2","2","E4-02","UE","Test de SeaNear en C01","plans/F0-F2 T28","CP","CPP",3,"pend","MVP"),
("E4-04","F2-T29 Mecánicas desde marcadores y auditoría R10","SpawnElement: catapulta, tanque, quad, trampolín, gaviotas","3","3","E4-02","UE","Cada mecánica activada en PIE 4P sin Find nulo","plans/F0-F2 T29","CP","CPP",3,"pend","MVP"),
("E4-05","F2-T30 Vegetación en ATN_BeachDecorField","","4","4","E4-02","UE","Vegetación a cota fija en C01","plans/F0-F2 T30","CP","CPP",3,"pend","MVP"),
("E4-06","F2-T31 Catálogo Coop, elección y viaje","UTN_CoopMapCatalog, TravelURL","5","5","E4-02","UE","Lobby → LVL_Coop_C01 y CP01","plans/F0-F2 T31","CP","CPP",3,"pend","MVP"),
("E4-07","F2-T32 CP01 (mapa propio de Claude)","600 × 600 m con generador camino y puentes naturales","8","8","E2-03,E2-04","agente Python + game-designer","CP01 ≤ 1,1 M tri y recorrible","plans/F0-F2 T32; P02","PY","PY",2,"pend","MVP"),
("E4-08","F2-T33 Importar CP01 y C01","","3","3","E2-16,E4-06,E4-07","UE","Ambos en el catálogo y cocinados","plans/F0-F2 T33","CP","CPP",3,"pend","MVP"),
("E4-09","F2-T34 PIE 4P gate F2","PktLag 150","6","6","E4-03,E4-04,E4-05,E4-08","Rodrigo + UE","Aceptación del plan §3.1 completa","plans/F0-F2 T34","QA","MAN",3,"pend","MVP"),
("E4-10","F2-T35 Clásico fuera del selector","LVL_Run sale del cocinado","2","2","E1-01","UE","Selector sin Clásico; cook sin LVL_Run","plans/F0-F2 T35","CP","CPP",3,"pend","MVP"),
("E4-11","F2-T36 ATN_MatchGameModeBase","Run → base abstracta; rescatar ReviveImmunitySeconds","3","3","E4-10","UE","ProcMap y BeachRace heredan de la base nueva; tests verdes","plans/F0-F2 T36","CP","CPP",3,"pend","MVP"),
("E4-12","F2-T37 LVL_Demo01 fuera","Y resolver el stash wip LVL_Demo01","1","1","E4-08","UE","Mapa y script borrados; stash resuelto","plans/F0-F2 T37","CP","CPP",3,"pend","MVP"),
("E4-13","Botones de mapa en la pizarra del general","Desviación 3 del plan F0-F2","4","4","E4-06","UE","Elegir mapa Coop sin consola","plans/F0-F2 desviación 3","CP","CPP",3,"pend","MVP"),
("E4-14","C-1 Revivir y DBNO","Interactuar sobre el huevo fantasma","8","10","E4-11","UE","Tests de revivir verdes; revivir en PIE 4P","01-Coop §1.3, §12","CP","CPP",6,"pend","MVP"),
("E4-15","K-1 Reglas Coop","Derrota, victoria, continuar (−50 %), dificultad, estado","18","24","E0-10,E4-14","UE","Tests T-01 a T-07 verdes","01-Coop §12","CP","CPP",6,"pend","MVP"),
("E4-16","C-2a Piezas de puzzle N4, N1, M1, M3","Orden de menor coste","22","30","E0-13","UE","Cada pieza con test y en una plantilla del catálogo","01-Coop §6.2; Catálogo puzzles §2","CP","CPP",6,"pend","MVP"),
("E4-17","C-2b Piezas de puzzle M4, M2, N6, N2, N5, N3","","21","29","E4-16","UE","Las 15 plantillas montables por datos","01-Coop §6.2; Catálogo puzzles §2","CP","CPP",6,"pend","MVP"),
("E4-18","K-2 Escala de puzzles por jugadoras","P-1, P-2","6","9","E4-17","UE","Plantillas válidas con 1, 2, 3 y 4 jugadoras (test)","01-Coop §6.3","CP","CPP",6,"pend","MVP"),
("E4-19","Fusión de enemigos intocables (E-12, X-1..X-4)","Tras la fusión de TN_BeachGiantCrab/Enemy/ToyTank","2","3","E4-09","UE + Rodrigo (coordina)","Ficheros liberados sin conflicto","01-Coop Q10","CP","CPP",6,"pend","MVP"),
("E4-20","C-3 Enemigos X-1 a X-4 y ajustes","≈ 16 ajustes por enemigo y O-06","35","43","E4-19","UE","Cada enemigo con test de decisión y visto en PIE","01-Coop §4, §12","CP","CPP",6,"pend","MVP"),
("E4-21","K-3 Cangrejo guardián","E-12","8","10","E4-20","UE","Guardián escala con jugadoras (test)","01-Coop §4.3","CP","CPP",6,"pend","MVP"),
("E4-22","K-4 Reserva de la caja","FTNCoopLootPool","4","6","E0-11","UE","Test de reparto de la reserva","01-Coop §5","CP","CPP",6,"pend","MVP"),
("E4-23","K-5 Interfaz Coop","§7.2","14","20","E12-02","UE","Pantallas de §7.2 con estado replicado","01-Coop §7.2","UI","CPP",6,"pend","MVP"),
("E4-24","K-6 Progresión y recompensas","Cascos y conchas persistentes","10","14","E4-15","UE","Recompensa persiste tras reiniciar","01-Coop §2.2","CP","CPP",6,"pend","MVP"),
("E4-25","C-6 Red, presupuestos e instrumentación del Coop","Pooling en E0-14","16","22","E4-15","UE","Presupuestos de §9 cumplidos en PIE 4P","01-Coop §8-9","CP","CPP",6,"pend","MVP"),
("E4-26","C-7 Pruebas comunes","T-08 a T-12, T-20 a T-32","12","16","E4-17","test-automator","Tests verdes","01-Coop §10","CP","CPP",6,"pend","MVP"),
("E4-27","K-7 Contenido de CP01","Puzzles, enemigos, cajas y retoque a mano","20","28","E4-17,E4-20","game-designer + UE","Duración 12-18 min con 3 jugadoras (telemetría)","01-Coop §3.3, §12","CP","CPP",6,"pend","MVP"),
("E4-28","K-8 Retoque de C01","","8","12","E4-27","game-designer + UE","C01 cumple las reglas medibles de §3.4","01-Coop §3.4","CP","CPP",6,"pend","MVP"),
("E4-29","K-9 Pruebas de reglas Coop","T-01..T-07, T-10, T-40..T-43","8","12","E4-15","test-automator","Tests verdes","01-Coop §10","CP","CPP",6,"pend","MVP"),
# ---------------- E5 ----------------
("E5-01","F0-T6 Dorado T0 del reparto","24 semillas × 3 dificultades","3","3","—","UE","Test dorado verde antes de tocar el reparto","plans/F0-F2 T6; 02-Carrera §11","BR","CPP",1,"pend","MVP"),
("E5-02","T1 Correcciones P1-P3","Castillo tras sprint, lanzadores huérfanos, arcos de catapulta","13","18","E5-01","UE","72 semillas: castillo intacto y 0 huérfanos","02-Carrera §7.2","BR","CPP",4,"pend","MVP"),
("E5-03","T2 Assets de tramo y curso","UTN_BeachStretchAsset, UTN_BeachRaceCourseAsset","6","8","E5-02","UE","Tramo cargable desde DataAsset (test)","02-Carrera §3.2","BR","CPP",4,"pend","MVP"),
("E5-04","T3 PlaceAuthored","Intervalos, rol Authored, pasadas fijas, máscara","12","16","E5-03","UE","Curso vacío → reparto idéntico bit a bit","02-Carrera §3.3","BR","CPP",4,"pend","MVP"),
("E5-05","T4 Red de tramos","Selección con enfriamiento y hash","6","8","E5-04","UE","Hash distinto → aviso; 4 máquinas iguales","02-Carrera §7.1","BR","CPP",4,"pend","MVP"),
("E5-06","T5 Editor de tramos","Proxy, volumen, Export/Import/Validate","16","22","E5-04","UE","Tramo que corta el paso rechazado al exportar","02-Carrera §7.4","BR","CPP",4,"pend","MVP"),
("E5-07","T6 Tests de tramos, curso fijo y sprint","","6","8","E5-05","test-automator","Tests verdes","02-Carrera §9","BR","CPP",4,"pend","MVP"),
("E5-08","T7 Pulido P4-P8","Ritmo, densidad, halo, equidad de las 2 filas, métricas","29","40","E5-07","UE","Cobertura primer tercio ≥ 66 %; equidad de 8 huevos (test)","02-Carrera §3.5, §9","BR","CPP",4,"pend","MVP"),
("E5-09","T9 P9 subflujos de RNG y nuevo dorado","","4","6","E5-08","UE","Nuevo dorado en commit aparte","02-Carrera §11","BR","CPP",4,"pend","MVP"),
("E5-10","Objetos N1 y N2","Actores, sonidos, pesos, pruebas","14","18","E5-02","UE","Ambos objetos en PIE 4P con atribución","02-Carrera §5.2","BR","CPP",4,"pend","MVP"),
("E5-11","Atribución del atacante","Struct + HUD","2","3","E5-10","UE","Aviso de aturdimiento con nombre del atacante","02-Carrera §6","BR","CPP",4,"pend","MVP"),
("E5-12","Aparición de objetos en la Carrera","Reaparición 5 s/15 s y caja de remontada con gaviota","6","8","E5-10","UE","Caja cae ante las 2 últimas cada 30-40 s (telemetría)","02-Carrera anexo; P41","BR","CPP",4,"pend","MVP"),
("E5-13","Proveedor de suelo seguro en la playa","ATN_BeachRaceGenerator implementa ITN_SafeGroundProvider","3","4","E2-08,E5-04","UE","Rescate de la playa por el proveedor (test)","plans/F0-F2 desviación 1","BR","CPP",4,"pend","MVP"),
("E5-14","Contenido: 6 tramos del primer lote","Con el editor T5","12","12","E5-06","game-designer","6 tramos validados y en rotación","02-Carrera §3.4","BR","CPP",4,"pend","MVP"),
("E5-15","Tope de conchas con 6+ jugadores","Si la partida pasa de 25 min","1","1","E16-06","UE","Partida de 8 ≤ 25 min","02-Carrera P2","BR","CPP",13,"pend","MVP"),
("E5-16","T8 Mallas y BP propios de tramo","","14","20","E5-14","UE + equipo de arte","Tramos con seña visual propia","02-Carrera §11","BR","CPP",14,"pend","Despues"),
("E5-17","N3 y ayuda de primer uso","Cubo tapón y tooltip","6","9","E5-10","UE","","02-Carrera §11","BR","CPP",14,"pend","Despues"),
("E5-18","Rasante volumétrica leve en la Carrera","P01 literal; solo si Rodrigo reabre la decisión 3","16","24","—","UE + agente Python","Recta con cambio de rasante sin romper el dorado","P01; Plan §1 dec. 3","BR","CPP",14,"cond","Despues"),
# ---------------- E6 ----------------
("E6-01","B1 Port del núcleo del buggy sin Cargo","HYBuggy → ATN_Buggy en Vehicles/","6","8","E0-01","UE","0 referencias a Cargo/Chip/Token; compila","03-Rally §3.1, §13","VH","CPP",5,"pend","MVP"),
("E6-02","B1 BuggySpec y buggy_measure","","3","4","E6-01","test-automator","Tests verdes y medida en pista de prueba","03-Rally §11.1","VH","CPP",5,"pend","MVP"),
("E6-03","B1 Física síncrona con subpasos","MaxSubstepDeltaTime 0,016667","4","6","E6-02","UE","Caparazón, catapulta y trampolín sin regresión","03-Rally §3; Plan §3.3","VH","CPP",5,"pend","MVP"),
("E6-04","B1 Pawn buggy con tortuga visual","UTN_CosmeticLook","8","12","E6-01","UE","4 buggies en PIE con tortugas visibles","03-Rally §3","VH","CPP",5,"pend","MVP"),
("E6-05","B1 Sync de turbo y mina","","6","6","E6-04","UE","Correcciones < 50 cm tras turbo (p.NetShowCorrections)","03-Rally §9","VH","CPP",5,"pend","MVP"),
("E6-06","B3 Trazado, puertas, vueltas, posiciones","","16","20","E6-04","UE","Posiciones correctas con 4 buggies (test)","03-Rally §5.1-5.3","VH","CPP",5,"pend","MVP"),
("E6-07","B3 Dirección contraria y atajos ilegales","TNRally::IsWrongWay puro","8","12","E6-06","UE","Test: contramano 1,5 s a > 20 km/h → aviso","03-Rally §5.4-5.5; Rally_Sistemas","VH","CPP",5,"pend","MVP"),
("E6-08","B3 Enderezar, reaparición y anti-vuelco","Flip a 4 s, mar/KillZ → último arco","10","14","E6-06","UE","Buggy volcado se endereza en ≤ 4 s","03-Rally §5.6-5.7","VH","CPP",5,"pend","MVP"),
("E6-09","B3 Salida, fin (20 s), rebufo y copa","Parrilla invertida por puntos; contrarreloj con 1","11","14","E6-06","UE","Copa de 3 carreras completa en PIE","03-Rally §5.8-5.9, anexo C","VH","CPP",5,"pend","MVP"),
("E6-10","B4 Colisiones, atropello, fricción y cámara","","18","25","E6-04","UE","Fricción por material medida en buggy_measure","03-Rally §13","VH","CPP",5,"pend","MVP"),
("E6-11","4 ítems sobre vehículo","Coconut, SandMine, HomingCrab, Sunscreen; RollLoot por puesto","10","14","E6-06","UE","Cada ítem cumple su fila de autoridad en PIE 4P","Plan §3.3; 03-Rally §6.2","VH","CPP",5,"pend","MVP"),
("E6-12","Aparición de cajas del Rally","Filas 3 s, dobles 10 s, caja de remontada","6","8","E6-11","UE","Filas reaparecen a 3 s (test)","03-Rally anexo D","VH","CPP",5,"pend","MVP"),
("E6-13","F6b Ruta por hitos, tallado y checkpoints","Corredor 12-16 m, pendiente ≤ 12°, checkpoints_uu","30","45","E2-03","agente Python","Validador del corredor verde en E01B","Plan §3.3; 03-Rally §4.3","PY","PY",5,"pend","MVP"),
("E6-14","F6b Presupuesto de malla del Rally","Voxel adaptativo, colisión simple decimada, streaming","20","30","E6-13,E2-04","agente Python + UE","≤ 12 MB por mapa y ≤ 1 M tri/km²","Plan §2.5; 03-Rally anexo C","PY","PY",9,"pend","MVP"),
("E6-15","B9 E01B completo","Túnel, puente, cauce y piloto IA","24","34","E6-13,E6-08","UE + agente Python","Piloto IA: 0 atascos y 0 vuelcos en 10 recorridos","03-Rally §4.3, §13","VH","CPP",9,"pend","MVP"),
("E6-16","B9 Lazo, circuito, Laps y ventana de arco","","12","16","E6-15","UE","I03-R con 1 vuelta completa","03-Rally §5.2","VH","CPP",9,"pend","MVP"),
("E6-17","B9 L10 Japón Rally","","8","12","E6-16,E2-22","agente Python + UE","Validador del corredor verde","03-Rally §4.2","VH","CPP",9,"pend","MVP"),
("E6-18","B9 I03-R Tortuga Magna","","8","12","E6-16","agente Python + UE","Circuito con lazo recorrible","03-Rally §4.2","VH","CPP",9,"pend","MVP"),
("E6-19","B2 Asientos biplaza","Conductora y artillera","12","16","E6-06","UE","2 tortugas en un buggy en 4 máquinas","03-Rally §3.3; Plan §7.2","VH","CPP",9,"pend","MVP"),
("E6-20","B2 A1 Lanzar (artillera)","","8","12","E6-19,E6-11","UE","La artillera lanza los 4 ítems","03-Rally §3.4","VH","CPP",9,"pend","MVP"),
("E6-21","B2 A2 Contrapeso","","10","14","E6-19","UE","Anti-vuelco +0,20 g medido","03-Rally §3.4","VH","CPP",9,"pend","MVP"),
("E6-22","B5 Motor, derrape y boost (FX y SFX)","UTN_BuggyEngineSynth y efectos de §8","15","20","E6-04","UE","Motor, derrape, boost y choque audibles y visibles","03-Rally §8; UI-FX F2","VH","CPP",9,"pend","MVP"),
("E6-23","B6 Interfaz del Rally","U7 velocímetro, posición, checkpoint, panel de artillera, pantallas","25","35","E6-09","UE","HUD completo con estado replicado","03-Rally §7; UI-FX U7","UI","CPP",9,"pend","MVP"),
("E6-24","B7 Skins del buggy","DT_BuggySkins, FTN_BuggyLook, M_BuggyPaint, pestaña de tienda","14","18","E6-04","UE","Skin comprada igual en 4 máquinas y persiste","03-Rally §12; P02","VH","CPP",9,"pend","MVP"),
("E6-25","B7 Importar el kit del buggy low poly","Pipeline Art/Source/Vehicles/Buggy","7","10","E13-01","UE + technical-artist","Kit importado con LOD y colisión","03-Rally §12; Plan §7.8","VH","CPP",9,"pend","MVP"),
("E6-26","B8 Red de 8 buggies","30/10 Hz y sonda de correcciones","6","6","E6-15","UE","Subida del anfitrión ≤ 140 KB/s con 8","03-Rally §9.2","VH","CPP",9,"pend","MVP"),
("E6-27","Atribuciones de MDE en el Rally","Créditos por mapa geográfico","2","2","E6-13","agente Python","Cada mapa geo con su fuente en créditos","Plan §3.3","PY","PY",9,"pend","MVP"),
("E6-28","B10 Pruebas del Rally","Unitarias y manuales","10","10","E6-26","test-automator + Rodrigo","Tests verdes; PIE 4P con 150 ms y 2 %","03-Rally §11","VH","CPP",9,"pend","MVP"),
("E6-29","Opción E de red (autoridad del conductor)","Solo si la sonda lo exige","20","30","E6-26","UE","Correcciones del conductor aceptadas","03-Rally §9; Plan F6d","VH","CPP",14,"cond","Despues"),
("E6-30","Países de Rally restantes (11)","8-12 h cada uno","88","132","E6-17","agente Python + UE","Cada país con corredor validado","03-Rally §13.2","VH","CPP",14,"pend","Despues"),
("E6-31","Resto de Después del Rally","A3-A5, expulsión y reenganche, trampolín de vehículo, marcas de derrape, bifurcación de E01B","63","87","E6-28","UE","","03-Rally §13.2","VH","CPP",14,"pend","Despues"),
# ---------------- E7 ----------------
("E7-01","Modo TcT: fases, reloj, conchas, muerte súbita","Y desconexión","14","18","E0-10","UE","Ronda a 8 sin errores en PIE","04-TcT §1-2, §12","TC","CPP",7,"pend","MVP"),
("E7-02","LastInstigator y atribución","Tests < 6 s puntúa, ≥ 6 s no","4","6","E7-01","UE","Tests de atribución verdes","04-TcT §1.3","TC","CPP",7,"pend","MVP"),
("E7-03","Reaparición en nidos con inmunidad","","4","6","E7-01","UE","Reaparece en el nido más alejado si hay rival a < 15 m (test)","04-TcT §1.4","TC","CPP",7,"pend","MVP"),
("E7-04","Loot por puntos","RollLoot con Norm","3","4","E7-01","UE","Test de pesos por puntos","04-TcT §5","TC","CPP",7,"pend","MVP"),
("E7-05","HUD de TcT (U8)","Marcador, «X te tiró», +1, flechas, avisos","10","14","E7-02","UE","Aviso de quién te tiró en 4 máquinas","04-TcT §6; UI-FX U8","UI","CPP",7,"pend","MVP"),
("E7-06","Tally y Champion por puntos","","4","6","E7-01","UE","Pantalla de fin por puntos","04-TcT §12","UI","CPP",7,"pend","MVP"),
("E7-07","Viento (ATN_WindGust)","","5","7","E7-01","UE","Ráfaga igual en 4 máquinas","04-TcT §3.2","TC","CPP",7,"pend","MVP"),
("E7-08","Barricadas y marcadores de P01","LVL_Bridges_P01","2","3","E2-16","UE","P01 con 8 nidos, 8 cajas, cofre, rampas","04-TcT §3.1","TC","CPP",7,"pend","MVP"),
("E7-09","Hundimiento (ATN_SinkingPlatform)","Servidor autoritativo con aviso de 5 s","10","14","E7-01","UE","Anillo baja a la vez en 4 máquinas (±5 cm)","04-TcT §3.3; Catálogo §6","TC","CPP",7,"pend","MVP"),
("E7-10","Objetos 1-5","Piedra, balón, tinta, pala, plátano","12","18","E7-04,E9-05","UE","Cada objeto cumple su aceptación del plan §3.4","04-TcT §5; Plan §3.4","TC","CPP",7,"pend","MVP"),
("E7-11","Iconos por render","render_preview.py sobre los borradores IA","3","4","E7-10","technical-artist","7 iconos PNG en Content","04-TcT K1","ART","ART",7,"pend","MVP"),
("E7-12","Aparición: caja del cielo con gaviota y cofre central","Máx. 2 cajas vivas; cofre a los 60 s","6","8","E7-04","UE","Caja cae cada 25-35 s cerca del grupo (telemetría)","04-TcT anexo; P40","TC","CPP",7,"pend","MVP"),
("E7-13","Mapas MVP: P01, A01 Diana, I01 Filipinas","","24","34","E7-08,E7-09,E2-22","game-designer + UE","Encuentro cada 15-20 s en playtest (telemetría)","04-TcT §12.3","TC","CPP",7,"pend","MVP"),
("E7-14","Pruebas y playtest 4P/8P","","12","16","E7-13","test-automator + Rodrigo","Tests Tortunabo.TcT.* verdes","04-TcT §10","TC","CPP",7,"pend","MVP"),
("E7-15","Objetos 6-8: dardo de noqueo, trabuco, garfio","Pistola de noqueo = ApplyKnockdown en servidor","17","25","E7-10,E9-05","UE","Cápsula tras noqueo igual en 4 máquinas (±10 cm)","04-TcT §5; Plan §7.7","TC","CPP",7,"pend","MVP"),
("E7-16","Gaviotas con suelta ajustada y cangrejos","","5","8","E7-01","UE","Suelta sobre tablero o meseta ≈ 70 %","04-TcT §12","TC","CPP",7,"pend","MVP"),
("E7-17","Corte de puentes en TcT","Lógica de modo sobre ATN_BridgeSpan","4","6","E2-20,E7-01","UE","Puente cortado deja caer a quien está encima en 4 máquinas","04-TcT §3.5","TC","CPP",7,"pend","MVP"),
("E7-18","Mapas fase B: A02, A05, L05 Venecia","","14","20","E7-13","game-designer + UE","Validadores y encuentro en playtest","04-TcT §12.3","TC","CPP",10,"pend","MVP"),
("E7-19","Aguja giratoria (A04)","","8","10","E7-01","UE","Aguja noquea igual en 4 máquinas","04-TcT §12","TC","CPP",14,"pend","Despues"),
("E7-20","Mapas TcT Después","A03, A04, A06, I02, I03-T, I05, países TcT","60","100","E7-18","game-designer + UE","","04-TcT §12.3","TC","CPP",14,"pend","Despues"),
# ---------------- E8 ----------------
("E8-01","Lógica del 2 vs 2","GameMode, GameState, equipos, rondas, puntuación, sabotaje, abandono (45 s)","30","42","E0-10,E4-15","UE","Encuentro al mejor de 3 completo con 4 en PIE","05-2vs2 §1, §13","DV","CPP",8,"pend","MVP"),
("E8-02","Agarre de rivales y zonas de contacto","ATN_TeamContactZone e inmunidades","10","14","E8-01","UE","Lanzar a rival en caparazón solo en zona común (test)","05-2vs2 §5.4; P35","DV","CPP",8,"pend","MVP"),
("E8-03","Empuje de pawn y RaiseEndTime en la compuerta","N5 y M4 vienen de E4-17","3","3","E4-17","UE","Compuerta de sabotaje sube 5 s (test)","05-2vs2 §4.4","DV","CPP",8,"pend","MVP"),
("E8-04","Interfaz 2 vs 2","U1, U4, U6 y parte de U9 (U2/U3 en E12-02)","29","41","E8-01,E12-02","UE","Marcador de 2 equipos y alerta de sabotaje en 4 máquinas","05-2vs2 §7; UI-FX §3.1","UI","CPP",8,"pend","MVP"),
("E8-05","Efectos 2 vs 2","F1 UTN_PuzzleCueSynth y F3 destello","11","15","E8-01","UE","Éxito/fallo/placa/palanca audibles","05-2vs2 §8; UI-FX F1, F3","DV","CPP",8,"pend","MVP"),
("E8-06","Mapa DV01_canal y validador de simetría","","14","20","E3-06,E8-01","game-designer + agente Python","Carriles simétricos (validador) y ronda de 4-6 min en PIE","05-2vs2 §3.5-3.6","DV","CPP",8,"pend","MVP"),
("E8-07","Pruebas y PIE 4P","","14","20","E8-06","test-automator + Rodrigo","Tests del modo verdes y encuentro de 4 completo","05-2vs2 §11","DV","CPP",8,"pend","MVP"),
("E8-08","Retirar el 2 vs 2 procedural de carriles","ETNProcGameMode::TwoVsTwo a Deprecado","2","3","E8-07","UE","Nada del 2 vs 2 viejo en el selector ni en el cocinado","UI-FX decisiones 1","DV","CPP",8,"pend","MVP"),
("E8-09","2 vs 2 Después","S2-S4, DV02, DV03, «¡Ya!», cartel, sala de práctica, pegamento de plantillas","47","67","E8-07","UE + game-designer","","05-2vs2 §13.2","DV","CPP",14,"pend","Despues"),
# ---------------- E9 ----------------
("E9-01","Pendiente en arena (CMC predicho)","Desde 12°, rozamiento ×0,3, freno ×0,4","5","7","E0-01","UE","Arena a 25°: > 200 cm/s tras 2 s; llano para < 0,8 s","Plan §3.5; G","PL","CPP",2,"pend","MVP"),
("E9-02","Rebote predicho en vuelo","Restitución 0,45, 60 % tangencial (solo en vuelo)","4","6","E9-01","UE","Pared a 400 → rebote (test)","Plan §3.5; 04-TcT K2","PL","CPP",2,"pend","MVP"),
("E9-03","Estampado autoritativo","ServerDiveSplat → StartBody con v reflejada","5","7","E9-02","UE","Pared a 700 → bola en la misma posición en 4 máquinas (±5 cm)","Plan §3.5, §7.7","PL","CPP",2,"pend","MVP"),
("E9-04","Predicción del dive","DiveDir en el saved move","6","6","E9-01","UE","0 correcciones > 50 cm al iniciar el dive","Plan §3.5","PL","CPP",2,"pend","MVP"),
("E9-05","Noqueo autoritativo","ServerFreezeRagdoll ampliado al noqueo; ragdoll cosmético","6","10","E9-04","UE","Cápsula tras noqueo igual en 4 máquinas (±10 cm)","Plan §3.5 punto 5","PL","CPP",2,"pend","MVP"),
("E9-06","Tests Tortunabo.Dive.*","Incluye caso negativo con parámetros actuales","2","3","E9-03","test-automator","Tests verdes","Plan §3.5","PL","CPP",2,"pend","MVP"),
("E9-07","Playtest del doble salto con el director","TN.Dive.Debug 1 y NetEmulation","2","2","E9-06","Rodrigo","Rodrigo valida lanzar, deslizar y estamparse","Plan §3.5; P02","QA","MAN",2,"pend","MVP"),
("E9-08","Regresión del torbellino del caparazón","Test y PIE del fix (kanban Done)","2","3","E0-01","UE + Rodrigo (PIE)","TN.Beach.Gull.Grab 2 + caparazón sin torbellino ni atravesar el mapa","Kanban; P04","PL","CPP",2,"pend","MVP"),
("E9-09","Ragdoll de muerte que rueda y se asienta","Posición final del servidor; revive donde queda","6","10","E9-05","UE","Posición final igual en 4 máquinas (±10 cm)","memoria project_ragdoll_red","PL","CPP",11,"pend","MVP"),
# ---------------- E10 ----------------
("E10-01","Puente tambaleante con Excitation del servidor","uint8 a 10 Hz; Dips visuales","4","4","E0-01","UE","p.NetShowCorrections sin correcciones en el puente 4P","Plan §4 P1","NET","CPP",2,"pend","MVP"),
("E10-02","Plataforma tambaleante del servidor","int8 a 15 Hz","3","3","E10-01","UE","Desfase < 5 cm (hoy 19-25)","Plan §4 P2","NET","CPP",2,"pend","MVP"),
("E10-03","Mina sin empujón local","","2","2","—","UE","Sin doble empujón en PIE 4P","Plan §4 P2","NET","CPP",2,"pend","MVP"),
("E10-04","Boost de ítems en FTNSavedMove_Turtle","","4","4","E9-04","UE","Corrección < 5 cm (hoy ≈ 30)","Plan §4 P2","PL","CPP",2,"pend","MVP"),
("E10-05","Trampolín: rebote en el CMC","","4","4","E10-01","UE","0 correcciones tras el rebote","Plan §4 P2","NET","CPP",2,"pend","MVP"),
("E10-06","Quad: compensación de lag y retirar ATN_QuadActor","","2","2","E10-01","UE","FTNTrapClock visual; ATN_QuadActor fuera","Plan §4 P2","NET","CPP",2,"pend","MVP"),
("E10-07","Estado persistente por OnRep (N-C, M4)","Mancha del caparazón y dobles caminos OnRep + multicast","4","6","E10-01","UE","Quien entra tarde ve la mancha","F_gaps N-C; Calidad M4","NET","CPP",11,"pend","MVP"),
("E10-08","Viabilidad de voz con 8 personas","Ancho de banda del anfitrión, códec, RPC Unreliable actual frente a Steam Voice/EOS","4","6","—","agente de investigación (agy)","Informe con KB/s medidos o calculados y recomendación","P43","DOC","DOC",11,"pend","MVP"),
("E10-09","Optimización de voz para 8","VAD/PTT, bitrate, relevancia por distancia/equipo","8","12","E10-08","UE","8 hablando: subida del anfitrión dentro del presupuesto de E10-10","P07 y P43 (OLVIDADO)","NET","CPP",11,"pend","MVP"),
("E10-10","Presupuesto de red con 8 por modo","NetUpdateFrequency, relevancia, dormancy; KB/s del anfitrión","8","12","E0-05","UE","Tabla de KB/s por modo con 8 (Coop 4) en build Development","P43","NET","CPP",11,"pend","MVP"),
("E10-11","Prueba de replicación con 8 clientes reales","Standalone y Steam","4","6","E10-10","Rodrigo + UE","8 clientes 15 min sin desincronía ([Desync] = 0)","P43","QA","MAN",11,"pend","MVP"),
("E10-12","Entrada tardía y reconexión en los modos nuevos","Coop, Rally, TcT, 2 vs 2","6","8","E0-09","UE","Reconexión a mitad de ronda en cada modo sin estado roto","Plan §3.1 Red; auditoría 08-18 #5","NET","CPP",11,"pend","MVP"),
# ---------------- E11 ----------------
("E11-01","Monkey: terminar y commitear","TN_Monkey* y TN_TestReport en curso","4","6","E0-01","UE","TN.Monkey 10 min en C01 y BeachRace sin ensure; informe en Saved","00 §2; P29","FW","CPP",1,"curso","MVP"),
("E11-02","TN.Stress: llevar los sistemas al límite","Escenario con 8 pawns, objetos y mecánicas; medir ms, KB/s, draw calls","6","8","E11-01","UE","Informe con el primer sistema que rompe presupuesto","00 §2; P29","FW","CPP",2,"pend","MVP"),
("E11-03","Rutina nocturna local de monkey y estrés","Antes de cada PR grande","2","3","E11-02,E1-07","devops-engineer","Informe diario en Saved/Reports","00 §2","FW","DOC",2,"pend","MVP"),
("E11-04","Perfilado de render de mapas","Nanite, colisión, draw calls, sombras en C01, CP01, P01 y E01B","6","8","E4-08","UE","stat unit ≤ 16,6 ms en la gama mínima fijada","P07 (map rendering)","FW","CPP",11,"pend","MVP"),
("E11-05","Coste de ítems y VFX con 8 jugadoras","","3","4","E0-14","UE","ms por ítem activo medido; ninguno > 0,2 ms","P07 (item optimization)","FW","CPP",11,"pend","MVP"),
("E11-06","Presupuestos por modo en Shipping","Coop §9, TcT §9, Rally §10","4","6","E11-04","UE","Todos los presupuestos cumplidos o con tarea abierta","01-Coop §9; 04-TcT §9; 03-Rally §10","FW","CPP",13,"pend","MVP"),
("E11-07","Tamaño del paquete","≤ 12 MB por mapa y ≤ 500 MB de terreno","2","3","E6-14","UE","Informe del .pak por carpeta","03-Rally anexo C","FW","CPP",13,"pend","MVP"),
("E11-08","Gama mínima de hardware","Fijar la referencia de los presupuestos","1","1","—","Rodrigo","Gama mínima escrita en Docs","01-Coop Q5","DOC","MAN",1,"pend","MVP"),
# ---------------- E12 ----------------
("E12-01","U5 Selector de modo y mapa","Cinco modos, requisito de jugadoras en rojo","13","17","E4-10","UE","Los 5 modos seleccionables desde el HQ","UI-FX §2.1, §3.1","UI","CPP",6,"pend","MVP"),
("E12-02","C-4 Interfaz común (incluye U2, U3)","Anillo de progreso, marcadores de compañera, flechas","25","36","E0-12","UE","Pantallas de 01-Coop §7.1 con estado replicado","01-Coop §7.1; UI-FX U2-U3","UI","CPP",6,"pend","MVP"),
("E12-03","C-5 Efectos y sonido comunes","§7.3 (F1 y F3 en E8-05)","14","19","E0-12","UE","Efectos de §7.3 disparados por mensajería","01-Coop §7.3","UI","CPP",6,"pend","MVP"),
("E12-04","U9 Tally y Champion por equipos","Arrival con dos caras, podio de pareja","10","14","E7-06","UE","Podio de pareja en 2 vs 2","UI-FX U9","UI","CPP",8,"pend","MVP"),
("E12-05","Textos de Briefing y Pausa","Quitar Clásico y 2 vs 2 viejo","1","2","E4-10","UE","0 menciones al Clásico","UI-FX §0.3","UI","CPP",6,"pend","MVP"),
("E12-06","U10 Cartel de primera vez","Pictogramas de puzzle","4","6","E12-02","UE","","UI-FX U10","UI","CPP",14,"pend","Despues"),
("E12-07","F4 +1 flotante y marcas de derrape F5","","8","11","E7-05","UE","","UI-FX F4-F5","UI","CPP",14,"pend","Despues"),
("E12-08","Vista previa del mapa en la carga y menú con miniaturas","","10","14","E12-01","UE","","Plan §3.6; UI-FX §4.6","UI","CPP",14,"pend","Despues"),
# ---------------- E13 ----------------
("E13-01","Buggy biplaza low poly (kit)","Cerrar Art/Source/Vehicles/Buggy con lámina","4","6","—","technical-artist + Rodrigo (lámina)","Presupuesto de tris y bbox del manifest; lámina aprobada","Plan §7.8; P09","ART","ART",1,"curso","MVP"),
("E13-02","Borradores IA pendientes","Decoración por idioma de los 10 países sin prop y piezas de puzzle sin borrador","8","12","E2-21","technical-artist","Cada borrador con validación OK y lámina en INDEX.md","Art/Library/IA/INDEX.md; P29","ART","ART",10,"pend","MVP"),
("E13-03","Lámina de la biblioteca IA para Rodrigo","","1","1","E13-02","technical-artist + Rodrigo","Rodrigo marca qué pasa al equipo de arte","INDEX.md","ART","ART",10,"pend","MVP"),
("E13-04","Encargo priorizado al equipo de arte","5 encargos del inventario y borradores elegidos","2","3","E13-03","Rodrigo + game-designer","Lista enviada con plazos","Inventario §7","DOC","DOC",10,"pend","MVP"),
("E13-05","Encargos de producto Steam","Key art, logotipo, plantilla de icono, cápsulas, kit del HQ","0","0","E13-04","equipo de arte","Entregados","Inventario §7; README modos","EXT","EXT",10,"pend","MVP"),
("E13-06","Sustituir borradores por modelos finales","Importar, LOD, colisión, referencias","10","15","E13-05","UE + technical-artist","0 referencias a SM_TN_* de borrador en Content","INDEX.md","ART","CPP",13,"pend","MVP"),
("E13-07","Pose de la tortuga al volante","Deseable","3","4","E6-19","technical-artist","","Plan §3.6","ART","ART",14,"pend","Despues"),
# ---------------- E14 ----------------
("E14-01","Mapa01 a Deprecado","LVL_Mapa01, mallas y Scripts/terrain_volumes/Mapa01","2","3","—","UE","Cook sin Mapa01; generadores de terrain_vol verdes","Limpieza §Decisión; P20","CL","CPP",12,"pend","MVP"),
("E14-02","Retirar C++ de la rejilla (2.1)","Tras aceptar borrar los BP movidos","3","4","E14-01","UE + Rodrigo (decide)","6.059 líneas fuera; build y tests verdes","Limpieza 2.1","CL","CPP",12,"pend","MVP"),
("E14-03","Python pospuesto (2.1)","gen_terrain_biomes, terrain_gen; chaikin/generate_path a terrain_vol","2","3","—","agente Python","Pytest verde","Limpieza 2.1","PY","PY",12,"pend","MVP"),
("E14-04","Run por chunks y LVL_Run (2.2, 2.3, 4.5)","Decisión de equipo","4","6","E4-11","UE + Rodrigo + equipo","LVL_Run y 14 BP en _Deprecado; build verde","Limpieza 2.2-2.3, 4.5","CL","CPP",12,"pend","MVP"),
("E14-05","MapVariantLoader y TerrainMeshTile (2.4, 4.8)","Tras F1","2","3","E4-12","UE","603 líneas fuera; vista previa por importador","Limpieza 2.4, 4.8","CL","CPP",12,"pend","MVP"),
("E14-06","SeagullActor, QuadActor y EnemySeagull (2.5, 2.6, Q11)","","2","3","E14-04","UE","Clases en Deprecado; build verde","Limpieza 2.5-2.6; 01-Coop Q11","CL","CPP",12,"pend","MVP"),
("E14-07","Visor de terreno (2.7) y LVL_TestMap (4.6)","Reanalizar huérfanos (~2.300 líneas)","3","5","E14-04","UE","Informe de huérfanos y movidos","Limpieza 2.7, 4.6","CL","CPP",12,"pend","MVP"),
("E14-08","Propuestas a Alvaro y Mokius (4.1-4.4, 4.9-4.11)","","1","2","—","Rodrigo","Respuesta de cada autor","Limpieza lote 4","DOC","MAN",12,"pend","MVP"),
("E14-09","Calidad M2, M3, M9, M12","Tormenta por nombre, ButtonGroup, versión de ajustes, cargas síncronas","6","10","—","UE","Cada punto cerrado con test o log","Calidad-Codigo","CL","CPP",12,"pend","MVP"),
("E14-10","Calidad M5 y M6","TortugaCharacter.h y cabeceras con implementación","16","24","E9-05","UE","Unidades que incluyen TortugaCharacter.h < 40","Calidad M5-M6","CL","CPP",12,"pend","MVP"),
("E14-11","Calidad M7, M8, M11","Equilibrado a datos, emotes, rutas /Game duplicadas","14","20","E0-11","UE","0 literales /Game duplicados","Calidad M7, M8, M11","CL","CPP",12,"pend","MVP"),
("E14-12","Calidad M13 y splits de ficheros","BuildStructures, PauseMenu, BeachRaceGameMode, MP_GameInstance, Settings, GullZone, ProcFauna","22","32","E14-10","UE","Ningún fichero tocado > 800 líneas","Calidad top 10","CL","CPP",12,"pend","MVP"),
("E14-13","Calidad LOW (L1, L2, L4, L5, L7, L8)","","3","5","—","UE","Cada punto cerrado","Calidad LOW","CL","CPP",12,"pend","MVP"),
# ---------------- E15 ----------------
("E15-01","Textos nuevos de los 5 modos en 13 idiomas","LOCTEXT + .po","8","12","E12-01","UE","0 FText::FromString visibles nuevos","Localizacion.md; P34–P36","LOC","CPP",13,"pend","MVP"),
("E15-02","Restos sin localizar (M10, L6, 37 FromString)","","4","6","—","UE","Auditoría de textos visibles a 0","F_gaps #3; Calidad M10, L6","LOC","CPP",13,"pend","MVP"),
("E15-03","Fuentes CJK Noto","Descargar e integrar","2","3","—","UE","ja, ko, zh sin tofu","F_gaps #3","LOC","CPP",13,"pend","MVP"),
("E15-04","Nombres de mapas y humor por idioma","Sin rótulos políticos","1","2","E2-25","game-designer","Lista revisada","Catálogo §6 preguntas 5-6","LOC","DOC",13,"pend","MVP"),
("E15-05","LQA nativa","Coordinar revisores externos","2","2","E15-01","Rodrigo","Informe LQA por idioma","F_gaps #3","LOC","MAN",13,"pend","MVP"),
("E15-06","Validar ajustes y audio","","4","4","—","UE + Rodrigo","Checklist de ajustes completo","F_gaps #2","LOC","CPP",13,"pend","MVP"),
("E15-07","Logros y rich presence","Estado «En la carrera, ronda N» y unirse desde amigos","20","20","E1-05","UE","≥ 10 logros desbloqueables en Steam real","F_gaps #8","LOC","CPP",13,"pend","MVP"),
# ---------------- E16 ----------------
("E16-01","Gate playtest PIE 4P + Standalone loopback","Kanban In Progress (checklist 10 puntos)","3","4","E0-01","Rodrigo","Checklist marcado con commit","Kanban; memoria playtest","QA","MAN",1,"curso","MVP"),
("E16-02","Recorrer P01 y E01 en PIE","Kanban Backlog","2","2","—","Rodrigo","Notas de ajuste por mapa","Kanban","QA","MAN",1,"pend","MVP"),
("E16-03","Actualizar el checklist de playtest con los modos nuevos","","2","3","E16-01","game-designer","Checklist con secciones de los 5 modos","memoria project_playtest_checklist","DOC","DOC",4,"pend","MVP"),
("E16-04","Playtest Shipping en Steam, iteración 1 (tras F2)","16 h por iteración","16","16","E4-09,E1-05","Rodrigo + UE","Checklist completo en Steam real con 4","F_gaps §4.1","QA","MAN",6,"pend","MVP"),
("E16-05","Playtest Shipping en Steam, iteración 2 (Carrera y tortuga)","","16","16","E5-09,E9-07","Rodrigo + UE","Checklist completo","F_gaps §4.1","QA","MAN",7,"pend","MVP"),
("E16-06","Playtest Shipping en Steam, iteración 3 (TcT, 2 vs 2, Rally)","","16","16","E7-14,E8-07,E6-28","Rodrigo + UE","Checklist completo","F_gaps §4.1","QA","MAN",11,"pend","MVP"),
("E16-07","Playtest Shipping en Steam, iteración 4 (release candidate)","","16","16","E15-07,E1-12","Rodrigo + UE","Checklist completo con 8","F_gaps §4.1","QA","MAN",13,"pend","MVP"),
("E16-08","Playtest de diseño Coop (3-4)","","3","4","E4-28","Rodrigo","Duración y dificultad medidas","01-Coop §10.3","QA","MAN",6,"pend","MVP"),
("E16-09","Playtest de ritmo de la Carrera con 8","","3","3","E5-08","Rodrigo","Duración de partida medida","02-Carrera P2","QA","MAN",4,"pend","MVP"),
("E16-10","Playtest de la copa de Rally","","3","3","E6-28","Rodrigo","10 copas: < 60 % de victorias de un tipo (solo/biplaza)","03-Rally §1","QA","MAN",9,"pend","MVP"),
("E16-11","Revisión adversarial por épica","Codex adversarial-review en cada fusión grande (6)","6","6","—","code-reviewer + codex","0 CRITICAL/HIGH abiertos por épica","CLAUDE global (delegación)","QA","DOC",13,"pend","MVP"),
("E16-12","Auditoría de cobertura final","Repetir la auditoría de peticiones antes de fusionar a main","2","3","E16-07","architect-reviewer","0 peticiones OLVIDADAS","Docs/Auditoria-Cobertura-2026-09-29.md","DOC","DOC",13,"pend","MVP"),
]
